package lotto.domain.generator;

import java.util.List;
import lotto.domain.Lotto;
import lotto.domain.LottoMachine;
import lotto.domain.Money;

public interface LottoGenerator {
  List<Lotto> autoGeneratedLottoList(Money money);
}
