package lotto.view;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.Set;
import java.util.stream.Collectors;

public class InputView {
	private static final Scanner scanner = new Scanner(System.in);

	private static final String COMMA = ",";

	public void printLottoNumberUI(List<List<Integer>> autoGeneratedLottoNumbers) {
		printLottoNumber(autoGeneratedLottoNumbers);
		System.out.println();
	}

	public int printInputNoticeForPurchaseAmount() {
		print("구입금액을 입력해 주세요.");
		return scanner.nextInt();
	}

	public void printPurchaseLottoCount(int lottoTryCount) {
		print(String.format("%d개를 구매했습니다.", lottoTryCount));
	}

	public void print(String message) {
		System.out.println(message);
	}

	public void printLottoNumber(List<List<Integer>> autoGeneratedLottoNumbers) {
		for (List lottoNumber : autoGeneratedLottoNumbers) {
			print(lottoNumber.toString());
		}
	}

	public String printLastPrizeInput() {
		print("지난 주 당첨 번호를 입력해 주세요.");
		String lastWeekPrizeNumber = scanner.next();
		return lastWeekPrizeNumber;
	}

	public List<Integer> convertStringToInteger(String lastWeekPrizeNumberInput) throws IllegalArgumentException {
		List<Integer> lastWeekPrizeNumberList = new ArrayList<>();
		String[] lastWeekPrizeNumberArr = lastWeekPrizeNumberInput.split(COMMA);
		for (int i = 0; i < lastWeekPrizeNumberArr.length; i++) {
			Integer number = Integer.parseInt(lastWeekPrizeNumberArr[i].trim());
			lastWeekPrizeNumberList.add(number);
		}
		Set<Integer> validateSet = lastWeekPrizeNumberList.stream().collect(Collectors.toSet());
		if (validateSet.size() != 6) {
			throw new IllegalArgumentException();
		}
		return lastWeekPrizeNumberList;
	}


}
