package step2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class AutoGenerated {
    public static List<Integer> getLotto() {
        List<Integer> initLottoNumList = initLottoNum();
        Collections.shuffle(initLottoNumList);
        return initLottoNumList.subList(0, 6);
    }

    private static List<Integer> initLottoNum() {
        List<Integer> numList = new ArrayList<>();
        for (int i = 1; i <= 45; i++) {
            numList.add(i);
        }
        return numList;
    }
}
