package step2;

import java.util.ArrayList;
import java.util.List;

public class Lotto {
    public static final int LOTTO_PRICE = 1000;

    public static void main(String[] args) {
        int lottoNum = InputView.buyLotto() / LOTTO_PRICE;
        ResultView.printLottoCount(lottoNum);
        ArrayList<List<Integer>> lottoArray = getAutoLotto(lottoNum);
        ResultView.printLottoNum(lottoArray);
        List<Integer> lastWinner = InputView.getLastWinner();
    }

    private static ArrayList<List<Integer>> getAutoLotto(int lottoNum) {
        ArrayList<List<Integer>> lottoArray = new ArrayList<>(lottoNum);

        for (int i = 0; i < lottoNum; i++) {
            lottoArray.add(AutoGenerated.getLotto());
        }
        return lottoArray;
    }
}
