package step2;

import java.util.ArrayList;
import java.util.List;

import static step2.Calculator.*;

public class Lotto {
    public static final int LOTTO_PRICE = 1000;

    public static void main(String[] args) {
        int lottoNum = InputView.buyLotto() / LOTTO_PRICE;
        ResultView.printLottoCount(lottoNum);
        List<List<Integer>> lottoArray = getAutoLotto(lottoNum);
        ResultView.printLottoNum(lottoArray);
        List<Integer> lastWinner = InputView.getLastWinner();

        int[] resultArray = checkLottoNumber(lottoArray, lastWinner);
        ResultView.printDrawResult(resultArray);

        int revenue = calculateRevenue(resultArray);
        ResultView.printPercentage(calculatePercentage(lottoNum * LOTTO_PRICE, revenue));
    }

    private static int[] checkLottoNumber(List<List<Integer>> lottoArray, List<Integer> lastWinner) {
        int[] resultArray = new int[7];
        for (int i = 0; i < lottoArray.size(); i++) {
            int result = (countSameNumber(lastWinner, lottoArray.get(i)));
            resultArray[result] += 1;
        }
        return resultArray;
    }

    private static List<List<Integer>> getAutoLotto(int lottoNum) {
        List<List<Integer>> lottoArray = new ArrayList<>(lottoNum);

        for (int i = 0; i < lottoNum; i++) {
            lottoArray.add(AutoGenerated.getLotto());
        }
        return lottoArray;
    }
}
