package lotto;

import lotto.domain.Lotto;
import lotto.domain.LottoResult;
import lotto.view.InputView;
import lotto.view.ResultView;

import java.util.ArrayList;
import java.util.List;

public class LottoTVShow {
	private int purchaseAmount;

	private int lottoTryCount;

	private List<List<Integer>> autoGeneratedLottos = new ArrayList<>();

	private List<Integer> lastWeekPrizeNumbers = new ArrayList<>();

	Lotto lotto = new Lotto();

	LottoResult lottoResult = new LottoResult();

	InputView inputView = new InputView();

	ResultView resultView = new ResultView();


	public void broadcast() {
		printLottoShowIntro();

		printChooseLottoNumber();

		printLastWeekPrizeNumber();

		List<Integer> lottoResultList = compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber();

		lottoResult.arrangePrize(lottoResultList, Lotto.LOTTO_PRICE_PER_SHEET);
		resultView.printResult(lottoResultList, lottoResult);
	}

	private void printLottoShowIntro() {
		this.purchaseAmount = inputView.printInputNoticeForPurchaseAmount();
		this.lottoTryCount = lotto.calculateLottoCount(this.purchaseAmount);
		inputView.printPurchaseLottoCount(lottoTryCount);
	}

	private void printChooseLottoNumber() {
		autoGeneratedLottos = lotto.generateAutoLottoNumbers(lottoTryCount, autoGeneratedLottos);
		inputView.printLottoNumber(autoGeneratedLottos);
	}

	private void printLastWeekPrizeNumber() {
		String lastWeekPrizeNumber = inputView.printLastPrizeInput();
		lastWeekPrizeNumbers = inputView.convertStringToInteger(lastWeekPrizeNumber);
	}

	private List<Integer> compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber() {
		List<Integer> lottoResultList = new ArrayList<>();
		for (List<Integer> autoGeneratedLotto : autoGeneratedLottos) {
			int matchCount = lotto.getMatchCount(lastWeekPrizeNumbers, autoGeneratedLotto);
			lottoResultList.add(matchCount);
		}
		return lottoResultList;
	}
}
