package lotto;

import java.util.List;

import lombok.Getter;

@Getter
public class LottoPurchaseArgument {
	private final LottoPayAmounts lottoPayAmounts;
	private final List<Lotto> manualLottoNumbers;

	private LottoPurchaseArgument(LottoPayAmounts lottoPayAmounts, List<Lotto> lottos) {
		this.lottoPayAmounts = lottoPayAmounts;
		this.manualLottoNumbers = lottos;
	}

	public static LottoPurchaseArgument of(LottoPayAmounts payAmounts, List<Lotto> manualLottos) {
		return new LottoPurchaseArgument(payAmounts, manualLottos);
	}

	public int getAutoGeneratedLottosCount() {
		return lottoPayAmounts.getCountOfLotto(LottoKiosk.LOTTO_PRICE) - manualLottoNumbers.size();
	}
}
