package lotto;

import lotto.domain.GeneratedLotto;
import lotto.domain.Lotto;
import lotto.domain.LottoMatchResult;
import lotto.domain.LottoResult;
import lotto.model.LottoPrizePolicy;
import lotto.view.InputView;
import lotto.view.ResultView;

import java.util.ArrayList;
import java.util.List;

import static lotto.model.LottoPrizePolicy.isMatchBonusNumber;

public class LottoTVShow {
	public int purchaseAmount;

	Lotto lotto = new Lotto();

	LottoResult lottoResult = new LottoResult();

	public void start() {
		this.purchaseAmount = InputView.printInputNoticeForPurchaseAmount();
		List<GeneratedLotto> generatedLottos = lotto.generatePurchagedAutoLotto(purchaseAmount);
		GeneratedLotto lastWeekPrizeNumbers = InputView.printLastPrizeInput();
		int bonusNumber = InputView.printBonusNumberInput();

		List<LottoMatchResult> lottoResultList = this.compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber(lastWeekPrizeNumbers, generatedLottos, bonusNumber);

		this.lottoResult.arrangePrize(lottoResultList, Lotto.LOTTO_PRICE_PER_SHEET);
		ResultView.printResult(lottoResultList, lottoResult);
	}

	public List<LottoMatchResult> compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber(GeneratedLotto lastWeekPrizeNumbers, List<GeneratedLotto> generatedLottos, int bonusNumber) {
		List<LottoMatchResult> lottoResultList = new ArrayList<>();
		for (GeneratedLotto generatedLotto : generatedLottos) {
			boolean isMatchBonus = LottoPrizePolicy.isMatchBonusNumber( generatedLotto, bonusNumber);
			int matchCount = lotto.getMatchCount(lastWeekPrizeNumbers, generatedLotto);
			LottoMatchResult lottoMatchResult = new LottoMatchResult(matchCount, isMatchBonus);
			lottoResultList.add(lottoMatchResult);
		}
		return lottoResultList;
	}

}
