package lotto;

import lotto.domain.GeneratedLotto;
import lotto.domain.Lotto;
import lotto.domain.LottoResult;
import lotto.view.InputView;
import lotto.view.ResultView;

import java.util.ArrayList;
import java.util.List;

public class LottoTVShow {
	public int purchaseAmount;

	Lotto lotto = new Lotto();

	LottoResult lottoResult = new LottoResult();

	public void start() {
		this.purchaseAmount = InputView.printInputNoticeForPurchaseAmount();
		List<GeneratedLotto> generatedLottos = lotto.generatePurchagedAutoLotto(purchaseAmount);
		GeneratedLotto lastWeekPrizeNumbers = InputView.printLastPrizeInput();

		List<Integer> lottoResultList = this.compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber(lastWeekPrizeNumbers, generatedLottos);

		this.lottoResult.arrangePrize(lottoResultList, Lotto.LOTTO_PRICE_PER_SHEET);
		ResultView.printResult(lottoResultList, lottoResult);
	}

	private List<Integer> compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber(GeneratedLotto lastWeekPrizeNumbers, List<GeneratedLotto> generatedLottos) {
		List<Integer> lottoResultList = new ArrayList<>();
		for (GeneratedLotto generatedLotto : generatedLottos) {
			int matchCount = lotto.getMatchCount(lastWeekPrizeNumbers, generatedLotto);
			lottoResultList.add(matchCount);
		}
		return lottoResultList;
	}

}
