package lotto;

import java.util.List;

import lombok.Getter;

@Getter
public class LottoPurchaseArgument {
	private final LottoPayAmounts lottoPayAmounts;
	private final List<String> manualLottoNumbersString;

	private LottoPurchaseArgument(LottoPayAmounts lottoPayAmounts, List<String> manualLottoNumbersString) {
		this.lottoPayAmounts = lottoPayAmounts;
		this.manualLottoNumbersString = manualLottoNumbersString;
	}

	public static LottoPurchaseArgument of(LottoPayAmounts payAmounts, List<String> manualLottoNumbersString) {
		return new LottoPurchaseArgument(payAmounts, manualLottoNumbersString);
	}

	public int getAutoGeneratedLottosCount() {
		return lottoPayAmounts.getCountOfLotto(LottoKiosk.LOTTO_PRICE) - manualLottoNumbersString.size();
	}
}
