package lotto;

import lotto.domain.Lotto;
import lotto.domain.LottoResult;
import lotto.view.InputView;
import lotto.view.ResultView;

import java.util.List;

public class Main {

	private static LottoTVShow lottoTVShow = new LottoTVShow();

	private static Lotto lotto = new Lotto();

	private static LottoResult lottoResult = new LottoResult();

	private static InputView inputView = new InputView();

	private static ResultView resultView = new ResultView();

	public static void main(String[] args) {
		printLottoIntro();

		printChooseLottoNumber();

		printLastWeekPrizeNumber();

		List<Integer> lottoResultList = lottoTVShow.compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber();

		lottoResult.arrangePrize(lottoResultList, Lotto.LOTTO_PRICE_PER_SHEET);
		resultView.printResult(lottoResultList, lottoResult);
	}

	private static void printLottoIntro() {
		LottoTVShow.purchaseAmount = inputView.printInputNoticeForPurchaseAmount();
		LottoTVShow.lottoTryCount = lottoTVShow.calculateLottoCount(LottoTVShow.purchaseAmount);
		inputView.printPurchaseLottoCount(LottoTVShow.lottoTryCount);
	}

	private static void printChooseLottoNumber() {
		LottoTVShow.autoGeneratedLottos = lotto.generateAutoLottoNumbers(LottoTVShow.lottoTryCount);
		inputView.printLottoNumber(LottoTVShow.autoGeneratedLottos);

	}

	private static void printLastWeekPrizeNumber() {
		String lastWeekPrizeNumber = inputView.printLastPrizeInput();
		LottoTVShow.lastWeekPrizeNumbers = inputView.convertStringToInteger(lastWeekPrizeNumber);
	}
}
