package lotto.domain;

import java.util.ArrayList;
import java.util.List;

public class LottoAutoGenerator implements LottoGenerator {
    private final int count;

    public LottoAutoGenerator(PurchaseInformation purchaseInformation) {
        this.count = purchaseInformation.getAutoGeneratedCount();
    }

    @Override
    public List<Lotto> generateLottos() {
        final List<Lotto> generatedLottos = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            List<LottoNumber> lottoNumbers = LottoNumberGenerator.getLottoNumbers();
            generatedLottos.add(new Lotto(lottoNumbers));
        }
        return generatedLottos;
    }
}
