package lotto.domain;

import java.util.*;

public class LottoMachine {

  private Random random = new Random();
  private static final int END_NUMBER = 45;
  private static final int COST_CRETERION = 1000;
  private static final String INVALID_COST = "구매 금액은 1000원 이상이어야 합니다.";

  public int calculateLottoCount(int purchasePrice) {
    validatePurchasePrice(purchasePrice);
    return (purchasePrice / COST_CRETERION);
  }

  public void validatePurchasePrice(int purchasePrice) {
    if (purchasePrice < COST_CRETERION) {
      throw new IllegalArgumentException(INVALID_COST);
    }
  }

  public LottoList autoGeneratedLottoList(int lottoCount) {
    List<Lotto> lottoList = new ArrayList<>();
    for (int i = 0; i < lottoCount; i++) {
      List<LottoNumber> lottoNumberList = makeLottoNumber(END_NUMBER);
      lottoList.add(new Lotto(lottoNumberList));
    }

    return new LottoList(lottoList);
  }

  public List<LottoNumber> makeLottoNumber(int endNumber) {
    List<LottoNumber> lottoNumberList = new ArrayList<>();
    for (int i = 0; i < 6; i++) {
      lottoNumberList.add(LottoNumber.of(random.nextInt(endNumber) + 1));
    }
    Collections.sort(lottoNumberList);
    return lottoNumberList;
  }
}
