package lotto.domain;

import java.util.*;

public class LottoMachine {

    private Random random = new Random();

    public int calculateLottoCount(int purchasePrice) {
        return (purchasePrice/1000);
    }

    public List<Lotto> autoGeneratedLottoList(int lottoCount) {
        List<Lotto> lottoList = new ArrayList<>();
        for (int i=0; i<lottoCount; i++) {
            Set<LottoNumber> lottoNumberList = makeLottoNumber(45);
            lottoList.add(new Lotto(lottoNumberList));
        }

        return lottoList;
    }

    private Set<LottoNumber> makeLottoNumber( int endNumber) {
        Set<LottoNumber> lottoNumberList = new HashSet<>();
        for (int i = 0; i<6; i++) {
            lottoNumberList.add(new LottoNumber(random.nextInt(endNumber)+1));
        }

        return lottoNumberList;
    }
}
