package lotto.domain;

import java.util.*;

public class LottoMachine {

    private Random random = new Random();
    private static final int ENDNUMBER = 45;

    public int calculateLottoCount(int purchasePrice) {
        return (purchasePrice/1000);
    }

    public LottoList autoGeneratedLottoList(int lottoCount) {
        List<Lotto> lottoList = new ArrayList<>();
        for (int i=0; i<lottoCount; i++) {
            List<LottoNumber> lottoNumberList = makeLottoNumber(ENDNUMBER);
            lottoList.add(new Lotto(lottoNumberList));
        }

        return new LottoList(lottoList);
    }

    public List<LottoNumber> makeLottoNumber(int endNumber) {
        List<LottoNumber> lottoNumberList = new ArrayList<>();
        for (int i = 0; i<6; i++) {
            lottoNumberList.add(LottoNumber.of(random.nextInt(endNumber)+1));
        }
        Collections.sort(lottoNumberList);
        return lottoNumberList;
    }
}
