package lotto.domain;

import lotto.view.InputView;

import java.util.ArrayList;
import java.util.List;

public class LottoGenerator {
    private final int autoGeneratedCounts;
    private final int manualCounts;

    public LottoGenerator(final Money money, final int manualCounts) {
        this.autoGeneratedCounts = money.getLottoCount() - manualCounts;
        this.manualCounts = manualCounts;
    }

    private List<Lotto> generateManualLotto() {
        InputView inputView = new InputView();
        inputView.askManualLottoNumber();
        List<Lotto> manualLottos = new ArrayList<>();

        for (int i = 0; i < manualCounts; i++) {
            List<LottoNumber> lottoNumbers = new LottoManualGenerator(inputView.manualLottoNumber()).generateNumbers();
            manualLottos.add(new Lotto(lottoNumbers));
        }

        return manualLottos;
    }

    private List<Lotto> generateAutoLotto() {
        List<Lotto> autoLottos = new ArrayList<>();
        for (int i = 0; i < autoGeneratedCounts; i++) {
            List<LottoNumber> lottoNumbers = LottoAutoGenerator.getLottoNumbers();
            autoLottos.add(new Lotto(lottoNumbers));
        }
        return autoLottos;
    }

    public List<Lotto> getPurchasedLottos() {
        List<Lotto> purchasedLottos = new ArrayList<>(generateManualLotto());
        purchasedLottos.addAll(generateAutoLotto());
        return purchasedLottos;
    }

    public static WinningLotto generateWinningLotto() {
        InputView inputView = new InputView();

        Lotto winningLotto = new Lotto((new LottoManualGenerator(inputView.askLastPrizeNumber()).generateNumbers()));
        LottoNumber bonusNumber = new LottoNumber(inputView.askBonusPrizeNumber());
        return new WinningLotto(winningLotto, bonusNumber);
    }


}
