package lotto.domain;

import java.util.ArrayList;
import java.util.List;

public class LottoGenerator {
    private final int autoGeneratedCounts;
    private final int manualCounts;
    private final List<LottoNumbers> manualLottosNumbers;

    public LottoGenerator(final Money money, final ManualCount manualCount, final List<LottoNumbers> manualLottoNumbers) {
        this.autoGeneratedCounts = money.getLottoCount() - manualCount.getManualCounts();
        this.manualCounts = manualCount.getManualCounts();
        this.manualLottosNumbers = new ArrayList<>(manualLottoNumbers);
    }

    private List<Lotto> generateManualLotto() {
        List<Lotto> manualLottos = new ArrayList<>();
        for (LottoNumbers lottoNumber : manualLottosNumbers) {
            List<LottoNumber> manualLotto = new LottoManualGenerator(lottoNumber.getLottoNumbers()).generateNumbers();
            manualLottos.add(new Lotto(manualLotto));
        }
        return manualLottos;
    }

    private List<Lotto> generateAutoLotto() {
        List<Lotto> autoLottos = new ArrayList<>();
        for (int i = 0; i < autoGeneratedCounts; i++) {
            List<LottoNumber> lottoNumbers = LottoAutoGenerator.getLottoNumbers();
            autoLottos.add(new Lotto(lottoNumbers));
        }
        return autoLottos;
    }

    public List<Lotto> getPurchasedLottos() {
        List<Lotto> purchasedLottos = new ArrayList<>(generateManualLotto());
        purchasedLottos.addAll(generateAutoLotto());
        return purchasedLottos;
    }

    public WinningLotto generateWinningLotto(List<LottoNumber> winningLottoNumber, int winningBonus) {
        Lotto winningLotto = new Lotto((new LottoManualGenerator(winningLottoNumber).generateNumbers()));
        LottoNumber bonusNumber = new LottoNumber(winningBonus);
        return new WinningLotto(winningLotto, bonusNumber);
    }


}
