package lotto.domain;

import lotto.view.InputView;
import lotto.view.ResultView;

import java.util.List;

public class Main {

    public static void main(String [] args) {
        Lotto lotto = new Lotto();
        int ticketCount = lotto.countTicket(InputView.inputPurchaseAmount());
        int manualTicketCount = InputView.inputManualLottoCount();
        int autoGenerateTicketCount = lotto.countAutoGeneratedTicket(ticketCount, manualTicketCount);

        List<Ticket> tickets = lotto.generateTickets(autoGenerateTicketCount, InputView.inputManualLottoNumbers(manualTicketCount));

        ResultView.printLottoTicketCount(manualTicketCount, autoGenerateTicketCount);
        ResultView.printTickets(tickets);

        LottoMachine lottoMachine = new LottoMachine(lotto);
        GameResult gameResult = lottoMachine.playLotto(InputView.inputLastWeeksWinningNumbers(), InputView.inputBonusNumber());

        ResultView.printLottoResults(gameResult);
    }
}
