package lotto.domain;

import lotto.enums.MatchType;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Arrays;
import java.util.Map;

public class Money {

    private static final int ROUND_SCALE = 2;
    private static final int PRICE_PER_ONE_LOTTO = 1_000;

    private static int purchaseAmount;
    private static int manualTicketCount;

    public Money(int purchaseAmount, int manualTicketCount) {
        this.purchaseAmount = purchaseAmount;
        this.manualTicketCount = manualTicketCount;
    }

    static BigDecimal getBenefitRate(Map<MatchType, Integer> lottoResults) {
        BigDecimal totalWinAmount = new BigDecimal(calculateTotalAmount(lottoResults));
        return calculateBenefitRate(totalWinAmount, new BigDecimal(purchaseAmount));
    }

    static int calculateTotalAmount(Map<MatchType, Integer> lottoResults) {
        return Arrays.stream(MatchType.values())
                .mapToInt(i -> i.calculateTotalAmountForOneLotto(lottoResults.get(i)))
                .sum();
    }

    static BigDecimal calculateBenefitRate(BigDecimal totalWinAmount, BigDecimal purchaseAmount) {
        return totalWinAmount.divide(purchaseAmount, ROUND_SCALE, RoundingMode.DOWN);
    }

    static int countTicket() {
        return purchaseAmount / PRICE_PER_ONE_LOTTO;
    }

    public static int countAutoGeneratedTicket() {
        return countTicket() - manualTicketCount;
    }

    public static int countManualTicket() {
        return manualTicketCount;
    }

}