package lotto.domain;

/**
 * 구매 정보.
 */
public class PurchaseInformation {
    private static final String INVALID_MANUAL_COUNT = "구매 가능한 수량을 초과했습니다";
    /**
     * 입력받은 금액.
     */
    private final Money money;

    /**
     * 수동으로 구매한 갯수.
     */
    private final int manualPurchaseCount;

    public PurchaseInformation(Money money, int manualCount) {
        if (money.getLottoCount() < manualCount) {
            throw new IllegalArgumentException(INVALID_MANUAL_COUNT);
        }
        this.money = money;
        this.manualPurchaseCount = manualCount;
    }

    /**
     * 자동으로 생성된 갯수.
     */
    public int getAutoGeneratedCount() {
        return money.getLottoCount() - getManualPurchaseCount();
    }

    /**
     * 수동으로 생성된 갯수.
     */
    public int getManualPurchaseCount() {
        return manualPurchaseCount;
    }
}
