package lotto.model;

import lotto.util.NumbersCreator;

import java.util.*;

public class Buyer {

    private final List<Lotto> lottoes;
    private Buyer(final List<Lotto> lottoes) {
        this.lottoes = Collections.unmodifiableList(lottoes);
    }

    public static Buyer of(final int buyCount, final NumbersCreator numbersCreator) {
        List<Lotto> result = new ArrayList<>();
        for (int index = 0; index < buyCount; index++) {
            Lotto autoGeneratedLotto = createAutoGeneratedLotto(result, numbersCreator);
            result.add(autoGeneratedLotto);
        }
        return new Buyer(result);
    }

    public List<Lotto> value() {
        return this.lottoes;
    }

    private static Lotto createAutoGeneratedLotto(List<Lotto> result, NumbersCreator numbersCreator) {
        Lotto lotto = Lotto.of(numbersCreator);
        while (isDuplicateAutoGeneratedLotto(result, lotto)) {
            lotto = Lotto.of(numbersCreator);
        }
        return lotto;
    }

    private static boolean isDuplicateAutoGeneratedLotto(List<Lotto> result, Lotto lotto) {
        return result.contains(lotto);
    }
}
