package lotto.domain;

import lotto.domain.generator.AutoLottoGenerator;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class AutoLottoGeneratorTest {

  AutoLottoGenerator autoLottoGenerator;

  @BeforeEach
  void setUp() {
    autoLottoGenerator = new AutoLottoGenerator(5);
  }

  @Test
  @DisplayName("로또 자동 생산")
  public void autoGeneratedLottoList() {
    assertEquals(5, autoLottoGenerator.generatedLottoList().size());
  }

  @ParameterizedTest
  @ValueSource(ints = {0, 1, 2, 3, 4, 5})
  @DisplayName("랜덤으로 만든 로또 넘버가 1~45 사이의 숫자인지 확인")
  public void makeLottoNumber(int index) {
    assertThat(autoLottoGenerator.createSeed().get(index)).isBetween(1, 45);
  }
}
