package lotto.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class LottoMachineTest {

  @Test
  @DisplayName("로또 자동 생산")
  public void autoGeneratedLottoList() {
    LottoMachine lottoMachine = new LottoMachine();
    LottoList lottoList = lottoMachine.autoGeneratedLottoList(14);
    assertEquals(lottoList.getLottoCount(), 14);
  }

  @Test
  @DisplayName("입력 금액에 따라 구입한 로또 갯수 확인")
  public void calculateLottoCount() {
    LottoMachine lottoMachine = new LottoMachine();
    assertEquals(14, lottoMachine.calculateLottoCount(14000));
  }


  @Test
  @DisplayName("랜덤으로 만든 로또 넘버가 1~45 사이의 숫자인지 확인")
  public void makeLottoNumber() {
    LottoMachine lottoMachine = new LottoMachine();
    List<LottoNumber> lottoNumberList = lottoMachine.makeLottoNumber(45);

    assertThat(lottoNumberList.get(0).getNumber()).isBetween(1, 45);
  }

  @Test
  @DisplayName("1000원이상 금액 확인")
  public void validatePurchasePrice() {
    LottoMachine lottoMachine = new LottoMachine();
    assertThatIllegalArgumentException().isThrownBy(() -> {
      lottoMachine.validatePurchasePrice(900);
    });
  }
}
