package lotto.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class LottoNumberGeneratorTest {

    @DisplayName("로또 번호 자동 생성시 6개가 생성된다")
    @Test
    void createAutoGeneratedNumbers() {
        List<LottoNumber> lottoNumbers = LottoNumberGenerator.getLottoNumbers();

        assertThat(lottoNumbers.size()).isEqualTo(6);
    }
}
