package lotto.domain;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class LottoMachineTest {

    @Test
    public void autoGeneratedLottoList() {
        LottoMachine lottoMachine = new LottoMachine();
        LottoList lottoList = lottoMachine.autoGeneratedLottoList(14);
        assertEquals(lottoList.getLottoCount(),14);
    }

    @Test
    public void calculateLottoCount() {
        LottoMachine lottoMachine = new LottoMachine();
        assertEquals(14,lottoMachine.calculateLottoCount(14000));
    }


    @Test
    public void makeLottoNumber() {
        LottoMachine lottoMachine = new LottoMachine();
        List<LottoNumber> lottoNumberList = lottoMachine.makeLottoNumber(45);

        assertThat(lottoNumberList.get(0).getNumber()).isBetween(1,45);

    }
}
