package lotto.domain;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class PurchaseInformationTest {
    private PurchaseInformation purchaseInformation;

    @BeforeEach
    void setUp() {
        Money money = new Money(5000);
        int manualLottoCount = 2;
        purchaseInformation = new PurchaseInformation(money, manualLottoCount);
    }

    @DisplayName("구매 정보는 자동 생성 로또 갯수를 리턴한다.")
    @Test
    void lottoAutoGeneratedCount() {
        assertThat(purchaseInformation.getAutoGeneratedCount()).isEqualTo(3);
    }

    @DisplayName("구매 정보는 수동 생성 로또 갯수를 리턴한다.")
    @Test
    void lottoManualGeneratedCount() {
        assertThat(purchaseInformation.getManualPurchaseCount()).isEqualTo(2);
    }
}
