package lotto.controller;

import lotto.domain.*;
import lotto.view.InputView;
import lotto.view.ResultView;
import lotto.view.WinningNumbersParser;

public class LottoController {

    private static final int TICKET_PRICE = 1000;

    private final LottoMachine lottoMachine;
    private final LottoResultsService lottoResultsService;
    private final InputView inputview;
    private final ResultView resultView;

    public LottoController(LottoMachine lottoMachine, LottoResultsService lottoResultsService, InputView inputview, ResultView resultView) {
        this.lottoMachine = lottoMachine;
        this.lottoResultsService = lottoResultsService;
        this.inputview = inputview;
        this.resultView = resultView;
    }

    public void run() {
        int purchaseAmount = inputview.readPurchaseAmount();
        int numberPickedTickets = inputview.readNumberOfManuallyPickedTickets();
        int numberAutoGeneratedTickets = this.calculateAutoGeneratedNumbers(purchaseAmount, numberPickedTickets);
        LottoTickets tickets = lottoMachine.issueAuto(numberAutoGeneratedTickets);
        resultView.printLottoTickets(tickets);

        String winningNumbersInput = inputview.readWinningNumbers();
        WinningNumbers winningNumbers = WinningNumbersParser.parse(winningNumbersInput);
        int bonusNumber = inputview.readBonusNumber();
        winningNumbers.setBonusNumber(bonusNumber);

        LottoResult lottoResult = lottoResultsService.calculateResult(tickets, winningNumbers, purchaseAmount);
        resultView.printLottoResult(lottoResult);
    }


    private int calculateAutoGeneratedNumbers(int purchaseAmount, int numberPickedTickets) {

        if (purchaseAmount < TICKET_PRICE ) {
            throw new IllegalArgumentException("로또를 구매하기 적절한 금액이 아닙니다: " + purchaseAmount);
        }

        int all = purchaseAmount / TICKET_PRICE;
        int numberAutoCreatedTickets = all - numberPickedTickets;

        if (numberAutoCreatedTickets <= 0) {
            throw new IllegalArgumentException("수동으로 구매할 수 있는 개수를 넘었습니다: " + numberPickedTickets);
        }
        return numberAutoCreatedTickets;
    }
}
