package lotto.controller;

import lotto.domain.*;
import lotto.view.InputView;
import lotto.view.ResultView;

import java.util.List;


public class LottoGameController {

    private InputView inputView;
    private ResultView resultView;
    private LottoMachine lottoMachine;

    public LottoGameController() {
        inputView = new InputView();
        resultView = new ResultView();
        lottoMachine = new LottoMachine();
    }

    public void runGame() {
        int purchasePrice = drawPurchasePrice();

        int lottoCount = lottoMachine.calculateLottoCount(purchasePrice);
        drawLottoCount(lottoCount);

        LottoList lottoList = new LottoList(lottoMachine.autoGeneratedLottoList(lottoCount));
        drawLottoList(lottoList);

        List<LottoNumber> lastWeekWinningLotto = drawWinningLotto();

        LottoStatistics lottoStatistics = new LottoStatistics(lottoList.makeMatchingCount(lastWeekWinningLotto));

        drawLottoStatics(lottoStatistics);
        drawLottoEarningRate(lottoStatistics.calculate(purchasePrice));
    }

    private void drawLottoEarningRate(double earningRate) {
        resultView.printLottoEarningRate(earningRate);
    }

    private List<LottoNumber> drawWinningLotto() {
        return inputView.inputWinningLottoNumbers();
    }

    private void drawLottoStatics(LottoStatistics lottoStatistics) {
        resultView.printLottoStatics(lottoStatistics);
    }

    private void drawLottoList(LottoList lottoList) {
        resultView.printLottoList(lottoList);
    }

    private void drawLottoCount(int lottoCount) {
        resultView.printLottoCount(lottoCount);
    }

    private int drawPurchasePrice() {
        return inputView.inputPurchasePrice();
    }
}
