package lottery.domain;

import static java.lang.Integer.parseInt;
import static java.lang.String.valueOf;
import static java.util.Arrays.stream;
import static java.util.Collections.unmodifiableSet;
import static java.util.stream.Collectors.toSet;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import lottery.domain.numbergenerator.RandomNumberGenerator;

public class Lottery {

    private static final String INVALID_NUMBERS_MSG = "로또 번호는 총 6개의 숫자로 구성되어야합니다.";

    private static final String SEPARATOR = ",";

    private static final String BLANK_REGEX = "\\s";

    protected static final int LOTTERY_NUMBERS_SIZE = 6;

    private static final RandomNumberGenerator RANDOM_NUMBER_GENERATOR =
            new RandomNumberGenerator();

    private final Set<LotteryNumber> lotteryNumbers;

    public Lottery(Set<LotteryNumber> lotteryNumbers) {
        if(notHasSixNumbers(lotteryNumbers)) {
            throw new IllegalArgumentException(INVALID_NUMBERS_MSG);
        }
        this.lotteryNumbers = lotteryNumbers;
    }

    public static Lottery lotteryFactory(String source) {
        Set<LotteryNumber> collect = stream(separatedNumbers(source))
                .map(number -> new LotteryNumber(parseInt(number)))
                .collect(toSet());
        return new Lottery(collect);
    }

    public static Lottery autoGeneratedLottery() {
        Set<LotteryNumber> lotteryNumbers = new HashSet<>();
        while (lotteryNumbers.size() != LOTTERY_NUMBERS_SIZE) {
            lotteryNumbers.add(new LotteryNumber(RANDOM_NUMBER_GENERATOR.generatedNumber()));
        }
        return new Lottery(lotteryNumbers);
    }

    private static String[] separatedNumbers(String source) {
        return removeBlank(source).split(SEPARATOR);
    }

    private static String removeBlank(String source) {
        return source.replaceAll(BLANK_REGEX, "");
    }


    private boolean notHasSixNumbers(Set<LotteryNumber> lotteryNumbers) {
        return lotteryNumbers.size() != LOTTERY_NUMBERS_SIZE;
    }

    public int size() {
        return lotteryNumbers.size();
    }

    public Set<LotteryNumber> getNumbers() {
        return unmodifiableSet(this.lotteryNumbers);
    }

    public List<LotteryNumber> getSortedNumbers() {
        return new ArrayList<>(this.lotteryNumbers)
                .stream()
                .sorted(Comparator.comparingInt(LotteryNumber::hashCode))
                .collect(Collectors.toUnmodifiableList());
    }

    public int intersectionSize(Set<LotteryNumber> weeklyWinningNumbers) {
        return this.lotteryNumbers.stream()
                .filter(weeklyWinningNumbers::contains)
                .collect(Collectors.toSet()).size();
    }

    @Override
    public String toString() {
        return valueOf(lotteryNumbers);
    }
}
