package lottery.domain;

import static lottery.view.BlankPrintView.printBlank;
import static lottery.view.ResultView.printAutoGeneratedNumbers;
import static lottery.view.WinningNumberInputView.winningNumbers;

import lottery.view.PriceInputView;

public class LotteryApplication {

    public static void main(String[] args) {
        runLotteryApplication();
    }

    public static void runLotteryApplication() {
        LotteryPurchasePrice lotteryPurchasePrice =
                PriceInputView.buyLotteries();

        Lotteries lotteries = new Lotteries(lotteryPurchasePrice.getLotteries());

        printAutoGeneratedNumbers(lotteries.immutableGetLotteries());

        printBlank();

        WinningNumbers winningNumbers = winningNumbers();

        printBlank();



    }
}
