package lotto;

import lotto.domain.Lotto;
import lotto.domain.LottoMatchResult;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class LottoTVShowTest {

	@Test
	void 지난주_번호와_내가_산_로또번호를_비교한_결과를_얻는다_2등_당첨() {
		Lotto lastWeekPrizeNumber = new Lotto(new ArrayList<>(Arrays.asList(1,2,3,4,5,6)));
		LottoTVShow lottoTVShow = new LottoTVShow();
		List<Lotto> generatedLottos = new ArrayList<>();
		Lotto buyLottoNumber = new Lotto(new ArrayList<>(Arrays.asList(1,2,3,4,5,45)));
		generatedLottos.add(buyLottoNumber);

		LottoMatchResult actualMatchResult = lottoTVShow.compareLastWeekPrizeNumberWithAutoGeneratedLottoNumber(lastWeekPrizeNumber, generatedLottos, 45).get(0);
		assertThat(actualMatchResult).isEqualTo(new LottoMatchResult(5,true));
	}
}