package lottery.view;

import java.util.List;
import lottery.domain.Lottery;
import lottery.domain.constant.Rank;

public class ResultView {

    private static final String STATISTICS_RESULT_BANNER = "당첨 통계";

    private static final String SEPARATOR_LINE = "----------";

    private static final String STATISTICS_TEMPLATE = "%d개 일치 (%d원) -%d개";

    public static void printAutoGeneratedNumbers(List<Lottery> lotteries) {
        lotteries.forEach(lottery -> printSource(lottery.toString()));
    }

    public static void printStatisticsResult(Rank rank, int numberOfWins) {
        printSource(String.format(STATISTICS_TEMPLATE,
                rank.getCountOfMatch(),
                rank.getWinningMoney(),
                numberOfWins));
    }

    public static void printStatisticsResultBanner() {
        printSource(STATISTICS_RESULT_BANNER);
        printSource(SEPARATOR_LINE);
    }

    private static void printSource(String source) {
        System.out.println(source);
    }
}
