package lottery.view;

import java.util.List;
import lottery.domain.SixLotteryNumbers;

public class ResultView {

    public static void printAutoGeneratedNumbers(List<SixLotteryNumbers> lotteries) {
        lotteries.forEach(lottery -> printSource(lottery.toString()));
    }

    private static void printSource(String source) {
        System.out.println(source);
    }
}
